"""Added Restaurant model

Revision ID: 42c0f5920c5e
Revises: 2911d423efbe
Create Date: 2018-07-24 15:30:22.614203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42c0f5920c5e'
down_revision = '2911d423efbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('primary_lang', sa.String(length=2), nullable=True),
    sa.Column('extra_langs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('description_intl', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keywords', sa.Unicode(), nullable=True),
    sa.Column('address1', sa.Unicode(length=100), nullable=True),
    sa.Column('address2', sa.Unicode(length=100), nullable=True),
    sa.Column('city', sa.Unicode(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=12), nullable=True),
    sa.Column('province_code', sa.String(length=2), nullable=True),
    sa.Column('country', sa.Unicode(length=20), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('order_phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_city'), 'restaurant', ['city'], unique=False)
    op.create_index(op.f('ix_restaurant_lat'), 'restaurant', ['lat'], unique=False)
    op.create_index(op.f('ix_restaurant_long'), 'restaurant', ['long'], unique=False)
    op.create_index(op.f('ix_restaurant_name'), 'restaurant', ['name'], unique=False)
    op.create_table('account_restaurant',
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.ForeignKeyConstraint(['username'], ['account.username'], )
    )
    op.create_unique_constraint(None, 'role', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_table('account_restaurant')
    op.drop_index(op.f('ix_restaurant_name'), table_name='restaurant')
    op.drop_index(op.f('ix_restaurant_long'), table_name='restaurant')
    op.drop_index(op.f('ix_restaurant_lat'), table_name='restaurant')
    op.drop_index(op.f('ix_restaurant_city'), table_name='restaurant')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
